### ISSUE TITLE
update faq

### ISSUE THREAD

**Issue by basisbit** [htnyquist/ponemusic.net#1]
The line stating that there was no take-down request so far is not current any more. Might as well remove it / just not mention it.
https://github.com/htnyquist/ponemusic.net/blob/3ff1b1140bc2702c653133b64c8f153e83912fd1/src/faq.html#L71

**Comment by htnyquist** [comment]
If you want to send a PR, I'll merge it. But I don't think that'll be necessary at this point.

**Comment by basisbit** [comment]
If I may ask, would keeping the archive online and just removing the single songs that those people wanted taken down have been an option?

**Comment by htnyquist** [comment]
Right. That's a legitimate question.
So let me write another absurdly long wall of text, hopefully that answers something, and then I'll go try to think about something else.

Removing songs. That was what we expected we might have to do. That someone, at some point, might ask that we remove some of their content.
I tried to express that idea [from the start](https://desuarchive.org/mlp/thread/32881927/#q32903580) that, we can't please everyone, but the goal isn't to make artists feel like we're taking money away from them — even if I personally think we're doing the exact opposite. Musicians are the ones making this content in the first place, and although we cannot possibly contact everyone, we'd do what we can to respect their wishes.
Although we hoped that wouldn't happen (especially after 5 years), we did always say we would take that content down, and we would be very transparent about it. Even if that makes some archivist people think less of the archive. 

That would have meant looking for any duplicates under all albums/collabs/aliases — very carefully, because some of the tags can be missing or incorrect, leaving notices in the archive for those missing songs, developping a new page on the website to explain clearly that some content is now missing, why, by whom, and where to find it online (if at all possible). And then starting the release process.
Not everyone would have been happy, but that was the plan.
And in theory, if we could spend the time to comb through the affected file, scrub the archive clean, and code the new ["Lumen"](https://en.wikipedia.org/wiki/Lumen_(website)#Reception) page, all of this is still an option.

In practice — and please trust that I'm not trying to blame anyone else here — we were served with a bit more than the 'small fandom musician struggling to pay their rent' scenario we had originally pictured. And please understand that they have every right to do that, so don't go personally attacking our musicians. That helps nobody.
I deliberately put myself between a rock and a hard place, in a position where my project won't please everyone, but it depends on everyone to survive. People have a legal right to coordinate together and send grouped takedown notices if they want to. I just didn't plan for it to happen in this slowly shrinking, post-G4 fandom, and that's on me. We could always have kept things more quiet.

So now that I've bored you to death with context, let me answer your question. Why didn't we just do that?
Firstly, I think I've just not managed to convey the time it takes to maintain an archive of this size in normal times. Finding out overnight you have to track down a 1000+ songs+duplicates, replace them with appropriate notices for each artist, and all the other boring maintenance tasks that come with it (upgrading the scripts to understand placeholder notices before we can release, setting up tracking for those placeholder links to music websites so that we don't send people into pages that have long 404ed and let content quietly disappear, keeping and publishing the list of every removed song so people don't freak out, etc etc).
Well, it's not impossible, but it's certainly more than a single weekend of dedicated work to do properly.

Now, I already said I wasn't going to publish the notices themselves, because I really don't want to start a which hunt against those specific musicians.
But as a point of reference, in the last release we had added about 55 GB of content. That was work done over 6 months.
With the multiple notices we received we'd have to remove more than half of that. And that's before counting the unknown number of duplicates and collabs where a musician appears only as a secondary artist (e.g. featured singers).

We were down for a while, for "unscheduled maintenance".
I tried to sit down and do it. But that just made me feel like shit. Couldn't find the energy to keep going.
Turns out, undoing years of work can be harder than doing it in the first place.

And so that's what it says on the website.
It's not that the we *can't* track down and remove just those songs, I just physically cannot make myself put in the hours required to do it.
It's not that I *want* to quit, I just don't see another option.

So there you have it. Wall of text over. To all of our remaining artists in the fandom, I wish you the best. And now I'm going to try and go do something else until I stop feeling like shit.
Cheers.
